### ISSUE TITLE
[ENTRANCE] Handle deleted items properly

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/grottocenter-api#1075]
**Problem :**
Currently If I mark with is_deleted an entrance it will still be accessible the same way from the API.

In addition, Elastic Search will also continue to return it.

This issue is mostly to handle entities like Cave, Entrance, Massif, Document

For secondary entities like Description, History, Rigging, ... the solution for deleted items may be different

**Solution :** 
We need to return a minimalist entrance object when it is deleted. The goal of this object is to contain enough information to understand what was deleted, where I should go instead (redirect_to field) and potentially help a moderator later revert it if necessary.
But we should not provide information which may be potentially sensitive, as the entrance may have been deleted for the purpose of hiding this sensitive information...

> What about deleted documents?
> The astute reader may have noticed that if a document is deleted from MySQL, then that deletion will not be propagated to Elasticsearch. The following approaches may be considered to address this issue:
> MySQL records could include an "is_deleted" field, which indicates that they are no longer valid. This is known as a "soft delete". As with any other update to a record in MySQL, the "is_deleted" field will be propagated to Elasticsearch through Logstash. If this approach is implemented, then Elasticsearch and MySQL queries would need to be written so as to exclude records/documents where "is_deleted" is true. Eventually, background jobs can remove such documents from both MySQL and Elastic.
>  Another alternative is to ensure that any system that is responsible for deletion of records in MySQL must also subsequently execute a command to directly delete the corresponding documents from Elasticsearch.

Link: [How to keep Elasticsearch synchronized with a relational database using Logstash and JDBC](https://www.elastic.co/blog/how-to-keep-elasticsearch-synchronized-with-a-relational-database-using-logstash)

**Comment by Clm-Roig** [comment]
Related issue (not exactly a duplicate) : https://github.com/GrottoCenter/grottocenter-api/issues/695
