### ISSUE TITLE
[SEARCH] Don't find new entities

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#1107]
**Describe the bug**
Quand je créé un document je souhaite ensuite l'associer à une entrée. Mais si le document existe bien il n'est pas possible de le trouver vian le moteur de recherche et donc de l'associer à une entrée. Peut être que cela fonctionne si on attend que Logstach refasse son index au bout d'une heure

**To Reproduce**
Le document que je viens de créer https://grottocenter.org/ui/documents/145816
Faire une recherche de document avec Mine de charbon dans le titre

**Comment by urien** [comment]
C'est bien cela, les documents sont désormais accessibles

**Comment by bsoufflet** [comment]
Il faudra donc ajouter une mise à jour manuel de Elastic Search à la création d'un document.

**Comment by urien** [comment]
Un utilisateur a rapporté le même problème pour une entrée. Quand il l'a créée il a souhaité la retrouver et cela n'a pas été possible. Cela conduit certains utilisateurs à créer de nouveau l'entité qu'il vienne de créer en pensant que leur démarche n'a pas aboutie

**Comment by urien** [comment]
Le problème existe aussi quand on modifie un document (son titre). on ne peut plus le trouver tant que l'index n'a pas été mis à jour

**Comment by bsoufflet** [comment]
On a déjà la fonction `ElasticsearchService.create(` qui existe et qui est utilisé lors du create dans plusieurs services. Il faut maintenant le généraliser à tous les services qui INSERT (ou UPDATE) des entités indexées par ElasticSearch ...
