### ISSUE TITLE
[Entrance - Organization champs de localisation administrative] Création d'une route de mise à jour automatique

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#1210]
**Is your feature request related to a problem? Please describe.**
Désormais lorsqu'on créé une entrée ou une organisation les informations de localisation administrative sont renseignées automatiquement.
Pour les données historiques ces informations ont été saisies manuellement avec un seul champ pour les informations concernant les "départements" et les "régions".
Il convient de mettre à jour ces informations. cette mise à jour devra ensuite être réalisée périodiquement pour prendre en compte les modifications qui interviennent dans le nom des entités administrative, dans leur découpage.
La mise à jour des ces informations est nécessaire pour permettre de faciliter la recherche par entité administrative qui donne actuellement des résultats incomplets. @BTHOM en a besoin pour réaliser des patrouilles afin de vérifier et compléter les informations disponibles, département par département

**Describe the solution you'd like**
Création d'un route, accessibles aux administrateurs qui permette de lancer une mise a jour sur tous les pays /ALL
Une amélioration consisterait à permettre l'utilisation de cette route pour un seul pays à partir de son code ISO par exemple /FR
Disposer d'un module dans le menu des administrateurs serait agréable

**Comment by vmarseguerra** [comment]
Il n'y a pas besoin forcément besoin d'avoir une route dédiée, car les informations de localisation administrative sont aussi mises à jour lorsque que l'on modifie les coordonnées sur une entrance et une organisation, et toutes les données historiques ont été mises à jour avec un script.
