### ISSUE TITLE
[DB] suppression de documents

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#1272]
## Who can do it

Supprimer les documents qui sont déclarés "à supprimer"

## Dependant on issues

Le fichier ci-dessous contient les id des documents à supprimer
[kvV1qyEb.csv](https://github.com/GrottoCenter/grottocenter-api/files/13973357/kvV1qyEb.csv)

**Comment by vmarseguerra** [comment]
Tous les documents mentionnés ont été supprimés
