### ISSUE TITLE
[ADV SEARCH] Recherche BBS par pays

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/grottocenter-api#265]
Si je fais une recherche par région dans le BBS, "italie" par exemple, j'ai 998 résultats concernant la zone "Suisse"!. Est-ce une erreur des données BBS ou de la fonction recherche?

Si je recherche "espagne", ou "indonésie", ou "indonesie", ou "haiti", ou "Haïti", il y a zéro résultats.  

Je penche plutôt pour la fonction recherche qui marche pas

**Comment by Clm-Roig** [comment]
La recherche par pays utilise le champ "Pays ou région" : pour "espagne" il s'agit de "España (Spain) General" par exemple. Il faut donc rentrer "spain" pour obtenir ces résultats 🙂 

Ce problème peut difficilement être résolu dans la version actuelle vu le modèle de données mais on travaille à l'améliorer avec le nouveau modèle ultérieurement.

**Comment by Ospeleo** [comment]
oui, mais c'est assez inutilisable!

**Comment by Ospeleo** [comment]
solution: proposer un auto-complete sur le nom du pays. ca résoud le propbleme

**Comment by Ospeleo** [comment]
et pour Haiti, ou Indonésie, il faut taper quoi?

**Comment by Clm-Roig** [comment]
C'est pas vraiment un bug dans le sens où on n'est pas à l'origine des données du BBS. Donc à partir du moment où on met en place un outil de recherche simple dessus, on dépend du format des données. 

Après je suis bien d'accord, ça doit faire l'objet d'une amélioration, ce n'est vraiment pas pratique en l'état. 

Indonésie => Indonesia 
Haïti => Haiti (sans le tréma)

Pour le mélange "Suisse / Italie" c'est parce qu'il existe la région suivante : _Schweiz / Suisse (Switzerland) : Suisse romande / italienne, Fribourg; Genève; Jura; Neuchâtel; Valais; Vaud; Ticino_

**Comment by Ospeleo** [comment]
Oui, mais dans quelle langue on saisit le pays? 
en francais? (non), Italie ne marche pas
en anglais? (non), Italy ne marche pas
en italien? (oui), Italia marche.
**C'est pas cohérent.**
Et pour la chine, on va taper 中国 ？

Please： faire un fichier de langue avec les noms des pays, des continents, des zones, dans la langue utilisateur, qui va se référer aux noms dans la base de données.

**Comment by Ospeleo** [comment]
au pire, un auto-complete sur le nom du pays/de la zone permet au moins de vérifier qu'on a saisi un truc qui existe

**Comment by Clm-Roig** [comment]
On a chargé les données du BBS telles quelles, ce ne sont pas nous qui avons décidé quelle appellation utiliser et quelle cohérence suivre. Les données du BBS ont ce format pour des raisons historiques pour le moment 🙂 

On a une solution pour ce problème. Cette solution s'inscrit dans un remodelage général des données de Grottocenter (notamment par l'utilisation de pays traduits dans la langue de l'utilisateur, oui). Ça viendra plus tard dans l'année, c'est prévu.

**Comment by bsoufflet** [comment]
@Ospeleo : Nous avons actuellement 2 étudiants qui travaillent sur l'intégration de l'API de Here Map qui pourrait servir à ce type de chose. On tape le pays dans notre langue et Here renvoie au module de recherche le pays dans la langue du pays...
Cela permettrait ensuite de filtrer et de fournir des listes de région...

**Comment by Ospeleo** [comment]
@bsoufflet 
Oui. Il "suffit" de géoréférencer les zones du BBS (et ça, il faudra le faire un jour ou un autre)

Après plusieurs essais, j'ai l'impression que la recherche grottocenter actuelle est une recherche textuelle dans les noms de "zones BBS"

BBS fonctionne avec zones: 
par exemple
"Oceania (South Sea Islands, Pacific), Fidji, Kiribati (Iles Gilbert), Nauru, Nouvelle Calédonie (F), Polynesia, Salomon, Samoa West (USA), Tonga, Tuvalu, Vanuatu (Nouvelles Hebrides)"
" Italia : Campania, Benevento; Caserta; Napoli; Salerno"
"France Midi/Pyrénées. Ariège(09); Aveyron(12); Haute Garonne(31); Gers(32); Lot(46); Hautes Pyrénées(65); Tarn(81); Tarn et Garonne(82)"

- si je ne recherche QUE les fiches biblio du Gers, et bien avec la structure BBS, grottocenter renverra toutes les fiches biblio de France/MidiPy car BBS n'est pas plus détaillé que ça. 

On peut pas faire mieux à ce jour, et à moins de reprendre chaque fiche une à une.

- tu vois aussi que sur l'océanie, il y a des mélanges de langues: Nouvelles hebrides (nom traduit en francais), mais Polynesia (nom francais traduit en anglais), voir aussi : iles gilbert mais South Sea island.

Il faudra donc bien géoréférencer les zones du BBS, et ensuite, un moteur de noms géographiques (existant) traduira dans la langue de l'utilisateur.

ps: la recherche dans la bdd BBS originale existait en Francais ET en Anglais. donc il y a une entrée "nom de pays en francais" dans la base BBS, c'est sûr!

**Comment by bsoufflet** [comment]
@urien : Il y aurait il quelque chose à faire avec la moulinette des étudiants Polytech ? utiliser les API pour matcher 1 ou plusieurs positions par entrée BBS ? Il faudrait surement préparer le schema de BDD BBS avant pour que l'on puisse stocker ces nouvelles informations...

**Comment by urien** [comment]
@bsoufflet c'est possible ils faudrait partir de la branche d'Alain et remplacer la structure de la base par celle que Vincent a posé sur Slack le 6 mai. C'est la structure avec le BBS et cela ne changera pas

**Comment by Ospeleo** [comment]
Autre problème actuel: 

Deux zones/pays ayant des bouts de noms identiques renvoient des résultats incorrects

exemple: si je cherche les cavités de l'ain, "ain" retourne aussi tous les résultats d'espagne ("spain"), de russie (Russian federation), et surement d'autres. Ca fait 9800 résultats....

et il y en a plusieurs autres, j'ai pas chercher à tout trouver.
un auto-complete avec les zones existantes, ou une liste déroulante, ou un georéférencement des zones du BBS, resoud le problème.

**Comment by Clm-Roig** [comment]
#304 : 
Actuellement, il existe des pays que l'on peut atteindre avec le nom FR et ENG (Chine et China : 2 résultats FR VS 1200 résultats ENG)

**Comment by urien** [comment]
Ce problème pourra être traité quand le ticket https://github.com/GrottoCenter/grottocenter-front/issues/335 aura été pris en compte

**Comment by urien** [comment]
Demande intégrée dans https://github.com/GrottoCenter/grottocenter-front/issues/303
