### ISSUE TITLE
[DOC edition] Slow / impossible request when a file is attached to the document

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#699]
Quand on édite un document qui dispose d'un fichier attaché et qu'on valide, la requête n'aboutit pas ou elle est très lente à aboutir, sans qu'on ait ajouté ou supprimé de fichier. 

Pour reproduire : 
1. Créer un document avec un fichier attaché.
2. L'éditer (exemple : changer le nom, le résumé et ajouter un massif). Ne pas toucher aux fichiers !
3. Le valider.

La même requête avec un document qui n'a pas de fichier attaché aboutit bien en moins d'une seconde

**Comment by Clm-Roig** [comment]
Je viens de faire un test avec les infos suivantes : 
- Collection 
- Fichier de 5M 

J'ai édité le nom, la description (je n'ai pas touché au fichier toujours présent).
J'ai validé. 
Aucun problème constaté en terme de latence...

**Comment by Clm-Roig** [comment]
Je change le statut à "Info needed" jusqu'à ce qu'on trouve la procédure qui permet de reproduire le bug.

**Comment by urien** [comment]
Je supprime, le bug n'est pas assez clairement défini pour qu'une solution puisse être apportée
