### ISSUE TITLE
[DOC edition] A doc with file edited lost its file

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-api#722]
**Describe the bug**
When a doc submitted with files is edited, the link with the files are lost.

**To Reproduce**
1. Submit a document with a file.
2. Go to the "Document Validation" feature.
3. Display the doc details: the files should be visible.
4. Edit something on the document.
5. Display the doc details: the files have disappeared.

**Expected behaviour**
If files are not changed, they should remain when editing a document.

**Comment by Clm-Roig** [comment]
@urien Cette issue te semble bien rédigée concernant le problème des fichiers qui disparaissent à l'édition ?

**Comment by urien** [comment]
Oui c'est cela

**Comment by Clm-Roig** [comment]
Je viens de faire un test avec une issue possédant 2 fichiers. J'ai édité sa description et les fichiers étaient toujours là. J'ai même validé l'issue, pareil l'issue est toujours là... 

Le bug avait bien lieu qu'importe la modification effectuée ?

**Comment by urien** [comment]
Je se suis même pas sûr d'avoir fait une modification. En réfléchissant c'était peut être pour associer le document à un document parent. J'ai donc changé de type (>issue) et je l'ai associé à une collection que je venais de réaliser et valider dans une autre fenêtre.

**Comment by Clm-Roig** [comment]
Je vais ajouter un test pour le moment. 
Tant que le bug ne réapparaît pas, je laisse avec le label "Info needed" jusqu'à ce qu'on trouve la procédure pour le reproduire.

**Comment by urien** [comment]
ok,
Je vais faire des tests et les documenter durant le WE

**Comment by urien** [comment]
Le problème semble réglé
