### ISSUE TITLE
[MASSIF] Delete

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#736]
La route api/v1/massifs/delete/id ne doit être accessible qu'aux administrateurs
Les massifs qui ont le champ isDeleted à true ne doivent pas être indexés par Logstach

Lorsqu'un administrateur demande à supprimer un massif 

- Le champ isDeleted est passé à true pour le massif concerné
- Pour les documents le champ massif est remplacé par null s'il est égal a id du massif concerné
- Dans la table de jonction entrance/réseau (qui doit être créée) les lignes correspondant au massif à supprimer, sont supprimées

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-api/pull/1307
