### ISSUE TITLE
[ORGANIZATION] Delete Merge

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#737]
Il y a deux situations : soit la demande correspond à une suppression soit à une suppression avec fusion avec une autre organisation

Dans les deux cas
La route api/v1/organizations/delete/id ne doit être accessible qu'aux administrateurs
Les organisations qui ont le champ isDeleted (dans t_grotto) à true ne doivent pas être indexées par Logstach

Lorsqu'un administrateur demande à supprimer une organisation

- Le champ isDeleted (dans t_grotto) est passé à true pour le massif concerné

S'il s'agit seulement d'une suppression

- Dans les autres tables les champs ayant l'id de l'organisation à supprimer comme valeur prennent la valeur null
- Dans les tables de jonctions les lignes ayant l'id de l'organisation a supprimer dans le champ massif, sont supprimées

S'il s'agit d'une suppression avec fusion avec une autre organisation

- Le Champ is_merged_with (dans t_grotto) prend la valeur de l'organisation avec laquelle l'organisation supprimée est fusionnée
- Dans les table de jonction les lignes ayant l'id de l'organisation à supprimer sont remplacées par l'id de l'organisation avec laquelle l'organisation supprimée est fusionnée
- De mêmes dans les tables ayant un champ Organisation

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-api/pull/1307
