### ISSUE TITLE
[PERSON] Delete Merge

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#738]
Il y a deux situations : soit la demande correspond à une suppression soit à une suppression avec fusion avec une autre personne

Dans les deux cas
La route api/v1/persons/delete/id ne doit être accessible qu'aux administrateurs
Les personnes qui ont le champ isDeleted (dans t_caver) à true ne doivent pas être indexées par Logstach

Lorsqu'un administrateur demande à supprimer une personne

- Le champ isDeleted (dans t_caver) est passé à true pour la personne concernée

S'il s'agit seulement d'une suppression

- Dans les table les champs ayant l'id de la personne supprimée comme valeur prennent pour valeur l'id de la personne Unknow

S'il s'agit d'une suppression avec fusion avec une autre personne

- Le Champ is_merged_with (dans t_caver) prend la valeur de la personne avec laquelle la personne supprimée est fusionnée

- Dans les tables les champs ayant pour valeur l'id de la personne à supprimer prennent pour valeur l'id de la personne avec laquelle la personne supprimée est fusionnée

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-api/pull/1316
