### ISSUE TITLE
[NOTIFICATIONS SYSTEM]

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-api#881]
## Cas d'utilisation 

Grâce à #880, les leaders pourront s'inscrire à des massifs ou à des pays. Une fois inscrit, ils doivent recevoir des notifications les informant des modifications effectuées sur les massifs / pays auprès desquels ils sont inscrits. 

## Fonctionnalités souhaités
Un bon système de notifications doit permettre d'identifier les choses suivantes : 
- Qui a déclenché la notification (`notifier`)
- Qui est concerné (`notified`)
- Une date de création (`date_inscription`)
- Une date de lecture (`read_at`). Si elle est nulle, la notification n'a pas été lue.
- L'entité concernée par la notification (une cavité, un massif, une description...). On se basera sur le pattern utilisé par la table `t_name` qui contient de nombreux id extérieurs mais avec un seul de non-nul (id_massif OU id_cave OU id_entrance OU id_description OU id_location OU id_document).
- Le type d'opération effectuée (création, édition, suppression, validation).

## Solutions technique

Il est nécessaire de : 
- [x] Créer une table `t_notification` pour stocker les notifications (voir ci-dessus)
- [x] Créer une table `t_notification_type` pour stocker le type d'opération concernée par la notification (voir ci-dessus)
- [x] Ajouter une colonne `send_notification_by_email` dans `t_caver` pour accepter le fait de recevoir les notifications par mail
- [x] Créer une route `GET api/v1/notifications/unread/count` pour obtenir le nombre de notifications non-lues d'un utilisateur
- [x] Créer une route `GET api/v1/notifications` obtenir la liste des notifications d'un utilisateur (route paginée)

Le module de création de notification sera créé ultérieurement. Il sera appelé dans les routes de création, édition, suppression et validation d'entités pour remplir la table des notifications.

### Références

https://tannguyenit95.medium.com/designing-a-notification-system-1da83ca971bc
https://stackoverflow.com/questions/15013713/database-schema-for-notification-system-similar-to-facebooks

**Comment by bsoufflet** [comment]
@urien @Clm-Roig Postgre ne semble pas le type de BDD idéal pour un système de notification mais je pense qu'il est tout de même préférable de s'en accommoder plutôt que de rajouter un 2ᵉ type de BDD adapté qui alourdirait le devOps et le dev en local ;)
Il faudra donc gérer manuellement depuis l'application le TTL des notifications. En effet, cette table risque de croitre très rapidement et de rendre l'app lente. 
Il me semble que cette table des notifications n'a pas d'objectif d'historisation à long terme et que l'on pourrait donc imaginer un cron ou bien un trigger ou qq chose d'autre pour simuler un TTL et supprimer automatiquement les notifications âgées de plus de X jours.
Dans la v2 de GC il y avait une vue très complexe sur la BDD MySQL qui avait un peu cet objectif de notification et qui permettait d'afficher le tableau de homepage listant toutes les dernières modifications de Grottocenter. Cette table des notifications (non filtré par massif ou pays) pour permettre d'afficher un tableau équivalent pour les modérateurs :)

**Comment by Clm-Roig** [comment]
Oui, je te rejoins sur le constat de la BD. Tout comme pour les names, la gestion de l'entité concernée par la notification n'est pas aisée... 

Effectivement, il faudra les supprimer. On peut imaginer un TTL très court si la notification est lue (une semaine ?) et un TTL un peu plus long pour les autres (un mois ?).

J'avais pensé à baser le système de notification sur les tables d'historisation, dans l'esprit "dernières contributions". Mais je me suis dit que ce serait mieux d'avoir un système indépendant et plus flexible qui pourra être utilisé pour bien d'autres choses.

**Comment by Clm-Roig** [comment]
J'ai ajouté la section suivante pour les préférences de notifications @bsoufflet :

> - [ ] Ajouter 1 colonne `send_notification_by_email` dans `t_caver` pour accepter le fait de recevoir les notifications par mail.

Je pense qu'on peut partir du principe que l'utilisateur ne peut pas masquer les notifications dans l'application pour le moment. Il suffira de rajouter une autre colonne si besoin est (pour les notifs mobiles par exemple).

**Comment by urien** [comment]
On peut partir avec une suppression des notifications après un mois, effectivement
