### ISSUE TITLE
[NOTIFICATION] Create and mark as read

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-api#882]
## Cas d'utilisation 

Grâce à #881, la base de données est prête à accueillir des notifications. Il convient désormais de créer lesdites notifications.

## Fonctionnalités souhaitées

À chaque fois qu'une entité et créée, modifiée, supprimée ou validée (**CMSV** est utilisé dans la suite de cette issue), une notification doit être créée. Sont notifiées les personnes qui sont abonnées à un massif ou un pays "lié" à l'entité en cours de CMSV (voir #880).

## Solution technique

Il est nécessaire de : 
- [x] Développer un `NotificationService` qui contiendra la méthode `create` qui se chargera de créer les notifications pour les personnes concernées par la modification en cours. 
- [x] Cette méthode enverra également un mail de notification.
- [ ] Utiliser ce service dans les fonctionnalités de CMSV déjà existantes.
- [x] Ajouter une route `POST api/v1/notifications/read` pour marquer une notification comme lue.

**Comment by bsoufflet** [comment]
Je pense que le type de notification doit etre paramétrable... On pourrait choisir à terme 0 ou plusieurs des choix suivants en tant qu'utilisateur (leader pour commencer) de grottocenter : 
- email
- notification dans l'app grottocenter uniquement (via une icone cloche par exemple)
- notification push  mobile (un jour peut etre !)
- notification whatsapp ou autre (un jour...)

**Comment by Clm-Roig** [comment]
Bonne idée, je rajoute cette fonctionnalité sur #880 qui prépare la BD aux notifications.
