### ISSUE TITLE
[Import CSV] AdapterError: Unexpected error from database adapter: relation ""public.t_document_duplicate"" does not exist"

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#949]
**Describe the bug**
Lors que je souhaite importer une fiche BBS qui existe déjà pour la mettre à jour, l'application détecte bien que c'est un doublon mais quand je lance l'import celui-ci plante et le fichier csv avec les erreur contient le message d'erreur ci-dessus

Voila le fichier csv que j'utilise
[BBS_gestion_doublons.csv](https://github.com/GrottoCenter/Grottocenter3/files/9176225/BBS_gestion_doublons.csv)
Je vais faire une démonstration devant la commission bibliographie de l'UIS demain après midi.

**Comment by Clm-Roig** [comment]
Je viens de créer les tables sur la BD de prod, ça devrait marcher si le problème ne vient que de là.

**Comment by Clm-Roig** [comment]
C'est ce bug dont tu me parlais pour le devis @urien ? Mon dernier commentaire sous-entend que je pensais avoir résolu le souci en créant les tables dans la BD en prod mais j'imagine que ce n'est pas le cas (?).

**Comment by urien** [comment]
Je viens de faire un test.
Désormais le doublon est bien détecté et importé.
![image](https://user-images.githubusercontent.com/1165144/209623186-32a7b673-5409-4974-91d7-7992b01000cb.png)
![image](https://user-images.githubusercontent.com/1165144/209623224-fd9e82bf-317e-4e93-a64a-f5be380287a0.png)

Je peux sélectionner le doublon dans https://grottocenter.org/ui/duplicates
![image](https://user-images.githubusercontent.com/1165144/209623278-bc8c97aa-0eab-4921-bde3-899382a6e869.png)
A ce niveau là le bouton supprimer ne fonctionne pas (j'ai l'impression que le duplicat est supprimé mais pas retiré de la liste)
Si je sélectionne le doublon le  tableau apparait bien
![image](https://user-images.githubusercontent.com/1165144/209623796-88cf28dd-7b62-4181-a230-9f1dd4bb4c09.png)
Le clic sur le bouton "il n'y a pas de doublon" ne provoque pas de changement d'affichage mais le doublon a été supprimé
Si je sélectionne un des deux doublons et que je soumets il n'y a pas de mise à jour de l'affichage. 
Quand je vais voir la fiche du document, la premiere fois la mise à jour ne s'est pas faite (Conservation de tous les champs d'origine et remplacement du titre par un  nouveau titire avec remplacement de MONTPIOLLIER par Montpiollier), je viens de recommencer et cela aboutit
https://grottocenter.org/ui/documents/144926
[scv64.csv](https://github.com/GrottoCenter/grottocenter-api/files/10306526/scv64.csv)

**Comment by urien** [comment]
Il y a un autre probléme... Potentiel. Lorsqu'on merge des documents ils apparaissent dans la liste des documents à valider. Comme j'avais fait deux fois la fusion du même document j'avais deux fois le même document à valider. Peut-être que cela ne pose pas de problème de fonctionnement. De manière pratique cela nécessite de faire une étape supplémentaire ce qui est contraignant

**Comment by urien** [comment]
Le problème décrit a été résolu. Des difficultés persistent mais elles ne correspondent  pas à ce qui est décrit ici
