### ISSUE TITLE
[Entrance Edit] impossible to modify an entrance as user

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#958]
**Describe the bug**
En tant qu'utilisateur (2 tests avec fredericurien@gmail.com et dlap)
Lorsqu'on édite les informations de base de l'entrée https://grottocenter.org/ui/entrances/9503
on a un message lorsqu'on valide, nous indiquant qu'on n'a pas le droit d'éditer la cavité
Cela fonctionne avec un compte d'administrateur

Cela semble être le cas avec d'autres cavités

**Comment by Clm-Roig** [comment]
Message d'erreur quand on édite en tant qu'utilisateur : 
`You are not authorized to mark an entrance as sensitive.`

Alors que c'est `isSensitive: false` qui est envoyé.

**Comment by Clm-Roig** [comment]
Corrigé par [1689b01](https://github.com/GrottoCenter/grottocenter-api/commit/1689b010e73a3f55dfaa319e44fdb39c295ccc3e)

Je déploie dans la foulée directement.

**Comment by Clm-Roig** [comment]
Tu peux réessayer @urien, c'est en ligne. Je teste aussi de ce pas.

**Comment by urien** [comment]
C'est bon cela fonctionne,

Merci je fais suivre l'info
