### ISSUE TITLE
[DOCUMENT create update] Internal error

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#979]
**Describe the bug**
Lorsque j'ai créé le document https://grottocenter.org/ui/documents/141307 les fichiers associés n'ont pas été enregistrés, ni la langue d'ailleurs.
Quand je souhaite rajouter des fichiers cela ne fonctionne pas. J'ai un message internal serveur error qui apparait. Dans la console j'ai cela

![image](https://user-images.githubusercontent.com/1165144/185087770-5b179cfa-5b64-407b-a622-97cd33505299.png)

Juste avant j'ai créé un document et cela a fonctionné
https://grottocenter.org/ui/documents/141306

**Comment by Clm-Roig** [comment]
Peut-être que pour ce genre d'erreurs (les `500` / `Internal Error`) il faudrait renvoyer l'erreur précise UNIQUEMENT si l'utilisateur est un admin non ? 

Normalement on cache l'erreur (notamment aux utilisateurs malveillants) pour des raisons de sécurité. Si ici, il n'y a que les admins qui peuvent y avoir accès, on reste securisé (sauf si un admin est malveillant mais c'est un autre problème ça...😅 )

**Comment by urien** [comment]
C'est réglé
