### ISSUE TITLE
[PRODUCTION DEBUG] Error are not logged anymore in CloudWatch

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/grottocenter-api#982]
I don't know why but since the refactoring of the responses sent by the server (I think, not sure), nothing is logged in the AWS' CloudWatch service. 

I'm losing a lot of time trying to understand what's going on when a bug appears on production only, a fix would be appreciated.

**Comment by Clm-Roig** [comment]
Bumping log level to "info" didn't solve the issue...

**Comment by bsoufflet** [comment]
API is not anymore on amazon AWS
