### ISSUE TITLE
[LOCATION] Add route and field to delete a Location

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-api#983]
**Is your feature request related to a problem? Please describe.**
Afin de pouvoir mettre en place https://github.com/GrottoCenter/grottocenter-front/issues/724

**Describe the solution you'd like**
Ajout dans la table t_location d'un champ bouléen isdeleted
Création de la route
Delete location/id
Cette route n'étant accessible qu'aux administrateurs

**Comment by vmarseguerra** [comment]
Completed with https://github.com/GrottoCenter/grottocenter-api/pull/1306
